import type { Quest } from "../interfaces";

export const quests: Quest[] = [
  {
    icon: "🚦",
    title: "Find a traffic light",
    titleId: "Temukan lampu lalu lintas",
    copy: "Photograph a traffic light.",
    copyId: "Foto lampu lalu lintas.",
    tag: "LOOK UP",
  },
  {
    icon: "🌱",
    title: "Find some grass",
    titleId: "Temukan rumput",
    copy: "Photograph a patch of grass.",
    copyId: "Foto sebidang rumput.",
    tag: "FEEL THE GROUND",
  },
  {
    icon: "🚗",
    title: "Spot a red car",
    titleId: "Temukan mobil merah",
    copy: "Photograph a red car.",
    copyId: "Foto mobil berwarna merah.",
    tag: "SPOT THE RED",
  },
  {
    icon: "🍃",
    title: "Find a new leaf",
    titleId: "Temukan daun baru",
    copy: "Photograph a leaf you have not noticed before.",
    copyId: "Foto daun yang belum pernah kamu sadari sebelumnya.",
    tag: "LOOK CLOSER",
  },
  {
    icon: "☁️",
    title: "Find a cloud shape",
    titleId: "Temukan bentuk awan",
    copy: "Photograph an interesting cloud.",
    copyId: "Foto awan dengan bentuk yang menarik.",
    tag: "LOOK UP",
  },
  {
    icon: "🌸",
    title: "Find a flower",
    titleId: "Temukan bunga",
    copy: "Photograph a flower.",
    copyId: "Foto sebuah bunga.",
    tag: "NOTICE COLOR",
  },
  {
    icon: "🪨",
    title: "Find a smooth stone",
    titleId: "Temukan batu halus",
    copy: "Photograph a smooth stone.",
    copyId: "Foto batu yang halus.",
    tag: "FEEL TEXTURE",
  },
  {
    icon: "🌳",
    title: "Find the tallest tree",
    titleId: "Temukan pohon tertinggi",
    copy: "Photograph the tallest tree nearby.",
    copyId: "Foto pohon tertinggi di dekatmu.",
    tag: "LOOK HIGH",
  },
  {
    icon: "🪶",
    title: "Find a feather",
    titleId: "Temukan bulu",
    copy: "Photograph something feather-light.",
    copyId: "Foto sesuatu yang seringan bulu.",
    tag: "FOLLOW THE BREEZE",
  },
  {
    icon: "🪑",
    title: "Find a place to sit",
    titleId: "Temukan tempat duduk",
    copy: "Photograph an outdoor seat.",
    copyId: "Foto tempat duduk di luar ruangan.",
    tag: "PAUSE HERE",
  },
  { icon: "🐦", title: "Spot a bird", titleId: "Temukan burung", copy: "Photograph a bird, perched or in flight.", copyId: "Foto seekor burung, hinggap atau terbang.", tag: "LISTEN FIRST" },
  { icon: "🦋", title: "Find a butterfly or insect", titleId: "Temukan kupu-kupu atau serangga", copy: "Photograph a butterfly, bee, or other small insect.", copyId: "Foto kupu-kupu, lebah, atau serangga kecil lainnya.", tag: "STAY STILL" },
  { icon: "💧", title: "Find a puddle", titleId: "Temukan genangan air", copy: "Photograph a puddle and what it reflects.", copyId: "Foto genangan air dan apa yang dipantulkannya.", tag: "LOOK DOWN" },
  { icon: "🌉", title: "Find a bridge", titleId: "Temukan jembatan", copy: "Photograph a bridge, big or small.", copyId: "Foto sebuah jembatan, besar atau kecil.", tag: "CROSS OVER" },
  { icon: "🏍️", title: "Spot a motorbike", titleId: "Temukan sepeda motor", copy: "Photograph a parked motorbike.", copyId: "Foto sepeda motor yang sedang parkir.", tag: "SPOT THE RIDE" },
  { icon: "🚲", title: "Find a bicycle", titleId: "Temukan sepeda", copy: "Photograph a bicycle.", copyId: "Foto sebuah sepeda.", tag: "SLOW DOWN" },
  { icon: "🐕", title: "Find a friendly pet or stray", titleId: "Temukan hewan peliharaan atau kucing/anjing jalanan", copy: "Photograph a dog or cat from a respectful distance.", copyId: "Foto anjing atau kucing dari jarak yang sopan.", tag: "KEEP YOUR DISTANCE" },
];
